# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-kYBk2eGDNL6oq72LeMdaMOtw47jRcb
"""

import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Flatten
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings('ignore')

# 1. Veri Okuma
if os.path.exists('/content/sample_data/powerconsumption.csv'):
    dosya_yolu = '/content/sample_data/powerconsumption.csv'
elif os.path.exists('/content/powerconsumption.csv'):
    dosya_yolu = '/content/powerconsumption.csv'
else:
    dosya_yolu = 'powerconsumption.csv'

df = pd.read_csv(dosya_yolu)
df['Datetime'] = pd.to_datetime(df['Datetime'])
df.set_index('Datetime', inplace=True)

# 2. Veri Ön İşleme ve Ölçeklendirme
def sutun_bul(aranan_kelime, sutunlar):
    for col in sutunlar:
        if aranan_kelime.lower().replace(" ", "") in col.lower().replace(" ", ""):
            return col
    return None

features = [sutun_bul('Temperature', df.columns),
            sutun_bul('Humidity', df.columns),
            sutun_bul('WindSpeed', df.columns),
            sutun_bul('Zone1', df.columns)]

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df[features])

# 3. Zaman Serisi Hazırlığı (Lookback: 24)
def create_sequences(data, lookback):
    X, y = [], []
    for i in range(len(data) - lookback):
        X.append(data[i:(i + lookback), :])
        y.append(data[i + lookback, 3])
    return np.array(X), np.array(y)

lookback = 24
X, y = create_sequences(scaled_data, lookback)

train_size = int(len(X) * 0.70)
val_size = int(len(X) * 0.15)

X_train, y_train = X[:train_size], y[:train_size]
X_val, y_val = X[train_size:train_size+val_size], y[train_size:train_size+val_size]
X_test, y_test = X[train_size+val_size:], y[train_size+val_size:]

def metrik_hesapla(gercek, tahmin):
    mae = np.mean(np.abs(gercek - tahmin))
    rmse = np.sqrt(np.mean((gercek - tahmin) ** 2))
    return rmse, mae

girdi_boyutu = (X_train.shape[1], X_train.shape[2])

# 4. Derin LSTM Modeli Eğitimi
model_lstm = Sequential([
    LSTM(64, return_sequences=True, input_shape=girdi_boyutu),
    LSTM(32, return_sequences=False),
    Dense(16, activation='relu'),
    Dense(1)
])

model_lstm.compile(optimizer=Adam(learning_rate=0.001), loss='mse')
early_stop_lstm = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

model_lstm.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=50, batch_size=32, callbacks=[early_stop_lstm], verbose=1)
tahmin_lstm = model_lstm.predict(X_test)
rmse_lstm, mae_lstm = metrik_hesapla(y_test, tahmin_lstm.flatten())

# 5. Derin MLP Modeli Eğitimi
model_mlp = Sequential([
    Flatten(input_shape=girdi_boyutu),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model_mlp.compile(optimizer=Adam(learning_rate=0.001), loss='mse')
early_stop_mlp = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

model_mlp.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=50, batch_size=32, callbacks=[early_stop_mlp], verbose=1)
tahmin_mlp = model_mlp.predict(X_test)
rmse_mlp, mae_mlp = metrik_hesapla(y_test, tahmin_mlp.flatten())

# 6. Karşılaştırmalı Sonuçların Raporlanması
sonuclar_tablosu = pd.DataFrame({
    'Model Versiyonu': [
        'Standart LSTM (Baseline)',
        'Derin LSTM (Geliştirilmiş)',
        'Standart MLP (Baseline)',
        'Derin MLP (Geliştirilmiş)'
    ],
    'Test RMSE': [0.012021, rmse_lstm, 0.013855, rmse_mlp],
    'Test MAE': [0.009029, mae_lstm, 0.009601, mae_mlp]
})

print("\nPerformans Karsilastirma Tablosu")
print("-" * 55)
print(sonuclar_tablosu.to_string(index=False))